//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    using DataAccess.DTO;
    using DataAccess.Entities;
    using DataAccess.Repository;
    using DataAccess.Context;
    using Microsoft.Extensions.Logging;
    
    public partial interface IAuditEntryService : IRepository<AuditEntry, AuditEntryDTO>
    {
    
    }
}
