//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Controllers
{
    using System;
    using System.Collections.Generic;
    
    using DataAccess.DTO;
    using DataAccess.Entities;
    using DataAccess.Interfaces;
    using DataAccess.Context;
    using Microsoft.Extensions.Logging;
    using Microsoft.AspNetCore.Mvc;
    
    [ApiController]
    [Route("api/[controller]")]
    public partial class AuditEntryController : ControllerBase
    {
        private readonly IAuditEntryService auditEntryService;
    
        public AuditEntryController(IAuditEntryService auditEntryService)
        {
            this.auditEntryService = auditEntryService;
        }
    
               
        [HttpGet]
        public async Task<IActionResult> GetListAsync()
        {
            var response = this.auditEntryService.GetAll();
            return await Task.FromResult(new JsonResult(response));
        }
            
        [HttpGet("{id}")]
        public async Task<IActionResult> GetOne(int? id)
        {
            var response = this.auditEntryService.GetOne(id);
            return await Task.FromResult(new JsonResult(response));
        }
    
        [HttpPost]
        public async Task<IActionResult> CreateAsync(AuditEntry entity)
        {
            var response = this.auditEntryService.Add(entity);
            return await Task.FromResult(new JsonResult(response));
        }
    }
}
