//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Services
{
    using System;
    using System.Collections.Generic;
    
    using DataAccess.DTO;
    using DataAccess.Entities;
    using DataAccess.Repository;
    using DataAccess.Interfaces;
    using DataAccess.Context;
    using Microsoft.Extensions.Logging;
    
    public partial class DepartmentService : BaseRepository<Department, DepartmentDTO>,  IDepartmentService
    {
    
        public DepartmentService(EmployeeContext context, ILogger<DepartmentService> logger): base(context, logger)
        {
        }
    
        public override Department Update(DepartmentDTO entity)
        {
            Department returnValue = null;
    
            try
            {
                var model = this.Context.Departments.Where(p => p.ID == entity.ID).FirstOrDefault();
                
    
                if (model != null)
                {
                
                    if (entity.ID != null)
                    {
                        model.ID = entity.ID.Value;
                    }
            
                    if (entity.Name != null)
                    {
                        model.Name = entity.Name;
                    }
            
                    if (entity.Location != null)
                    {
                        model.Location = entity.Location;
                    }
                            
                    this.Context.Departments.Update(model);
                    this.SaveChanges();
                    
                    // refresh entity
                    returnValue = this.Context.Departments.Where(p => p.ID == entity.ID).FirstOrDefault();;
    
                }
    
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message);
            }
    
            return returnValue;
    	}
    
    }
}
